Repository RenatoLuizCardoso/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2025-Backend, pull requests merged in 2025-05, with the labels that each got.

#55 :recycle: refactor: Renamed Addon and AddonCategory DTOs folder, and AddonType.java
  src/main/java/br/fatec/easycoast/dtos/addon/AddonFiltered.java
  src/main/java/br/fatec/easycoast/dtos/addon/AddonNoList.java
  src/main/java/br/fatec/easycoast/dtos/addon/AddonRequest.java
  src/main/java/br/fatec/easycoast/dtos/addon/AddonResponse.java
  src/main/java/br/fatec/easycoast/dtos/addonCategory/AddonCategoryFiltered.java
  src/main/java/br/fatec/easycoast/dtos/addonCategory/AddonCategoryNoList.java
  src/main/java/br/fatec/easycoast/dtos/addonCategory/AddonCategoryNoProduct.java
  src/main/java/br/fatec/easycoast/dtos/addonCategory/AddonCategoryProductFiltered.java
  src/main/java/br/fatec/easycoast/dtos/addonCategory/AddonCategoryRequest.java
  src/main/java/br/fatec/easycoast/dtos/addonCategory/AddonCategoryResponse.java
  src/main/java/br/fatec/easycoast/dtos/addonCategory/AddonType.java
Labels: bug, enhancement, P

#51 ✨ feat: Created the GET, POST and PUT endpoints from Restaurant
  src/main/java/br/fatec/easycoast/dtos/restaurant/RestaurantRequest.java
  src/main/java/br/fatec/easycoast/dtos/restaurant/RestaurantResponse.java
  src/main/java/br/fatec/easycoast/entities/Restaurant.java
  src/main/java/br/fatec/easycoast/mappers/RestaurantMapper.java
  src/main/java/br/fatec/easycoast/repositories/RestaurantRepository.java
  src/main/java/br/fatec/easycoast/resources/RestaurantController.java
  src/main/java/br/fatec/easycoast/services/RestaurantService.java
  src/main/resources/data.sql
Labels: enhancement, G

#59 ✨ feat: Created Customer Controller, Serivce, Entity and DTOs
  src/main/java/br/fatec/easycoast/dtos/customer/CustomerRequest.java
  src/main/java/br/fatec/easycoast/dtos/customer/CustomerResponse.java
  src/main/java/br/fatec/easycoast/entities/Customer.java
  src/main/java/br/fatec/easycoast/mappers/CustomerMapper.java
  src/main/java/br/fatec/easycoast/repositories/CustomerRepository.java
  src/main/java/br/fatec/easycoast/resources/CustomerController.java
  src/main/java/br/fatec/easycoast/services/CustomerService.java
  src/main/resources/data.sql
Labels: enhancement, G

#60 ✨feat: Updated User to Employee, Employee Entity, DTOs, Service and Controller
  src/main/java/br/fatec/easycoast/dtos/employee/EmployeeRequest.java
  src/main/java/br/fatec/easycoast/dtos/employee/EmployeeResponse.java
  src/main/java/br/fatec/easycoast/dtos/employee/Profile.java
  src/main/java/br/fatec/easycoast/dtos/user/UserProfile.java
  src/main/java/br/fatec/easycoast/dtos/user/UserRequest.java
  src/main/java/br/fatec/easycoast/dtos/user/UserResponse.java
  src/main/java/br/fatec/easycoast/entities/Employee.java
  src/main/java/br/fatec/easycoast/mappers/EmployeeMapper.java
  src/main/java/br/fatec/easycoast/mappers/UserMapper.java
  src/main/java/br/fatec/easycoast/repositories/EmployeeRepository.java
  src/main/java/br/fatec/easycoast/repositories/UserRepository.java
  src/main/java/br/fatec/easycoast/resources/EmployeeController.java
  src/main/java/br/fatec/easycoast/resources/UserController.java
  src/main/java/br/fatec/easycoast/services/CustomerService.java
  src/main/java/br/fatec/easycoast/services/EmployeeService.java
  src/main/java/br/fatec/easycoast/services/UserService.java
  src/main/resources/data.sql
Labels: enhancement, G

#42 ✨ feat: Created some endpoints for Cards
  src/main/java/br/fatec/easycoast/dtos/card/CardRequest.java
  src/main/java/br/fatec/easycoast/dtos/card/CardResponse.java
  src/main/java/br/fatec/easycoast/entities/Card.java
  src/main/java/br/fatec/easycoast/mappers/CardMapper.java
  src/main/java/br/fatec/easycoast/repositories/CardRepository.java
  src/main/java/br/fatec/easycoast/resources/CardController.java
  src/main/java/br/fatec/easycoast/services/CardService.java
  src/main/resources/data.sql
Labels: enhancement, G

#56 ✨ feat: added code for table
  src/main/java/br/fatec/easycoast/dtos/seat/SeatRequest.java
  src/main/java/br/fatec/easycoast/dtos/seat/SeatResponse.java
  src/main/java/br/fatec/easycoast/dtos/seat/SeatStatus.java
  src/main/java/br/fatec/easycoast/entities/Seat.java
  src/main/java/br/fatec/easycoast/mappers/SeatMapper.java
  src/main/java/br/fatec/easycoast/repositories/SeatRepository.java
  src/main/java/br/fatec/easycoast/resources/SeatController.java
  src/main/java/br/fatec/easycoast/services/SeatService.java
  src/main/resources/data.sql
Labels: enhancement

#61 ✨ feat: added scheduling code
  src/main/java/br/fatec/easycoast/dtos/scheduling/SchedulingRequest.java
  src/main/java/br/fatec/easycoast/dtos/scheduling/SchedulingResponse.java
  src/main/java/br/fatec/easycoast/entities/Scheduling.java
  src/main/java/br/fatec/easycoast/mappers/SchedulingMapper.java
  src/main/java/br/fatec/easycoast/repositories/SchedulingRepository.java
  src/main/java/br/fatec/easycoast/resources/SchedulingController.java
  src/main/java/br/fatec/easycoast/services/SchedulingService.java
Labels: enhancement, G

#57 ✨feat: added order service & imports
  src/main/java/br/fatec/easycoast/dtos/order/OrderRequest.java
  src/main/java/br/fatec/easycoast/dtos/order/OrderResponse.java
  src/main/java/br/fatec/easycoast/dtos/orderItem/OrderItemResponse.java
  src/main/java/br/fatec/easycoast/entities/Card.java
  src/main/java/br/fatec/easycoast/entities/Order.java
  src/main/java/br/fatec/easycoast/mappers/CardMapper.java
  src/main/java/br/fatec/easycoast/mappers/OrderItemMapper.java
  src/main/java/br/fatec/easycoast/mappers/OrderMapper.java
  src/main/java/br/fatec/easycoast/repositories/OrderRepository.java
  src/main/java/br/fatec/easycoast/resources/OrderController.java
  src/main/java/br/fatec/easycoast/services/CardService.java
  src/main/java/br/fatec/easycoast/services/OrderService.java
  src/main/resources/data.sql
Labels: enhancement

#91 🔧 chore: Added Prod and Dev mode, and postgres Connection
  pom.xml
  src/main/resources/application-dev.properties
  src/main/resources/application-prod.properties
  src/main/resources/application.properties
Labels: enhancement, M
