Repository RenatoLuizCardoso/FATEC-Itu-AMS-ADS-ProjetoIntegrador-2025-Backend, pull requests merged in 2025-04, with the labels that each got.

#5 Update issue templates
  .github/ISSUE_TEMPLATE/endpoint-issue.md
  .github/ISSUE_TEMPLATE/entity-issue.md
  .github/ISSUE_TEMPLATE/service-issue.md
Labels: documentation

#6 Added controller and generic issue
  .github/ISSUE_TEMPLATE/controller-issue.md
  .github/ISSUE_TEMPLATE/generic-issue.md
Labels: documentation

#41 ♻️ refactor: Organized the DTOs directory
  src/main/java/br/fatec/easycoast/dtos/category/CategoryRequest.java
  src/main/java/br/fatec/easycoast/dtos/category/CategoryResponse.java
  src/main/java/br/fatec/easycoast/dtos/item/ItemRequest.java
  src/main/java/br/fatec/easycoast/dtos/item/ItemResponse.java
  src/main/java/br/fatec/easycoast/dtos/item/ItemsOnly.java
  src/main/java/br/fatec/easycoast/dtos/product/ProductRequest.java
  src/main/java/br/fatec/easycoast/dtos/product/ProductResponse.java
  src/main/java/br/fatec/easycoast/dtos/square/SquareItems.java
  src/main/java/br/fatec/easycoast/dtos/square/SquareRequest.java
  src/main/java/br/fatec/easycoast/dtos/square/SquareResponse.java
  src/main/java/br/fatec/easycoast/dtos/user/UserProfile.java
  src/main/java/br/fatec/easycoast/dtos/user/UserRequest.java
  src/main/java/br/fatec/easycoast/dtos/user/UserResponse.java
  src/main/java/br/fatec/easycoast/entities/Square.java
  src/main/java/br/fatec/easycoast/entities/User.java
  src/main/java/br/fatec/easycoast/mappers/CategoryMapper.java
  src/main/java/br/fatec/easycoast/mappers/ItemMapper.java
  src/main/java/br/fatec/easycoast/mappers/ProductMapper.java
  src/main/java/br/fatec/easycoast/mappers/SquareMapper.java
  src/main/java/br/fatec/easycoast/mappers/UserMapper.java
  src/main/java/br/fatec/easycoast/resources/CategoryController.java
  src/main/java/br/fatec/easycoast/resources/ItemController.java
  src/main/java/br/fatec/easycoast/resources/ProductController.java
  src/main/java/br/fatec/easycoast/resources/SquareController.java
  src/main/java/br/fatec/easycoast/resources/UserController.java
  src/main/java/br/fatec/easycoast/services/CategoryService.java
  src/main/java/br/fatec/easycoast/services/ItemService.java
  src/main/java/br/fatec/easycoast/services/ProductService.java
  src/main/java/br/fatec/easycoast/services/SquareService.java
  src/main/java/br/fatec/easycoast/services/UserService.java
Labels: enhancement, good first issue, P

#52 ✨feat: Created the GET, POST and PUT endpoints for AddonCategory
  src/main/java/br/fatec/easycoast/dtos/Addon/AddonFiltered.java
  src/main/java/br/fatec/easycoast/dtos/Addon/AddonNoList.java
  src/main/java/br/fatec/easycoast/dtos/Addon/AddonRequest.java
  src/main/java/br/fatec/easycoast/dtos/Addon/AddonResponse.java
  src/main/java/br/fatec/easycoast/dtos/AddonCategory/AddonCategoryFiltered.java
  src/main/java/br/fatec/easycoast/dtos/AddonCategory/AddonCategoryNoList.java
  src/main/java/br/fatec/easycoast/dtos/AddonCategory/AddonCategoryNoProduct.java
  src/main/java/br/fatec/easycoast/dtos/AddonCategory/AddonCategoryProductFiltered.java
  src/main/java/br/fatec/easycoast/dtos/AddonCategory/AddonCategoryRequest.java
  src/main/java/br/fatec/easycoast/dtos/AddonCategory/AddonCategoryResponse.java
  src/main/java/br/fatec/easycoast/dtos/AddonCategory/addonType.java
  src/main/java/br/fatec/easycoast/dtos/item/ItemRequest.java
  src/main/java/br/fatec/easycoast/dtos/item/ItemResponse.java
  src/main/java/br/fatec/easycoast/dtos/product/ProductAddonCategoryFiltered.java
  src/main/java/br/fatec/easycoast/dtos/product/ProductFiltered.java
  src/main/java/br/fatec/easycoast/dtos/product/ProductRequest.java
  src/main/java/br/fatec/easycoast/dtos/product/ProductResponse.java
  src/main/java/br/fatec/easycoast/entities/Addon.java
  src/main/java/br/fatec/easycoast/entities/AddonCategory.java
  src/main/java/br/fatec/easycoast/entities/Item.java
  src/main/java/br/fatec/easycoast/entities/Product.java
  src/main/java/br/fatec/easycoast/entities/Square.java
  src/main/java/br/fatec/easycoast/mappers/AddonCategoryMapper.java
  src/main/java/br/fatec/easycoast/mappers/AddonMapper.java
  src/main/java/br/fatec/easycoast/mappers/ItemMapper.java
  src/main/java/br/fatec/easycoast/mappers/ProductMapper.java
  src/main/java/br/fatec/easycoast/mappers/SquareMapper.java
  src/main/java/br/fatec/easycoast/repositories/AddonCategoryRepository.java
  src/main/java/br/fatec/easycoast/repositories/AddonRepository.java
  src/main/java/br/fatec/easycoast/resources/AddonCategoryController.java
  src/main/java/br/fatec/easycoast/resources/AddonController.java
  src/main/java/br/fatec/easycoast/resources/CategoryController.java
  src/main/java/br/fatec/easycoast/resources/ItemController.java
  src/main/java/br/fatec/easycoast/resources/ProductController.java
  src/main/java/br/fatec/easycoast/services/AddonCategoryService.java
  src/main/java/br/fatec/easycoast/services/AddonService.java
  src/main/java/br/fatec/easycoast/services/ItemService.java
  src/main/java/br/fatec/easycoast/services/ProductService.java
  src/main/java/br/fatec/easycoast/services/exceptions/DatabaseException.java
  src/main/resources/data.sql
Labels: enhancement, G
